name = "piximmo-app"
main = "server/index.ts"
compatibility_date = "2025-10-01"
node_compat = true

[vars]
NODE_ENV = "production"

# Development environment
[env.development]
name = "piximmo-app-dev"
vars = { APP_ENV = "development", NODE_ENV = "development" }

# Production environment
[env.production]
name = "piximmo-app"
vars = { APP_ENV = "production", NODE_ENV = "production" }

# R2 Bucket bindings (for object storage)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "piximmo"
preview_bucket_name = "piximmo-dev"

# Observability configuration
[observability]
enabled = true

# Build configuration
[build]
command = "npm run build"

# Environment secrets (set via: wrangler secret put SECRET_NAME)
# Required secrets:
# - DATABASE_URL
# - SESSION_SECRET
# - JWT_SECRET
# - MAILGUN_API_KEY (optional, for email notifications)
# - REPLICATE_API_KEY (optional, for AI captioning)
# - MODAL_API_KEY (optional, for image analysis)
# - TIDYCAL_WEBHOOK_URL (optional, for scheduling integration)

# Routes (configure your custom domain here)
# [[env.production.routes]]
# pattern = "pix.immo/*"
# zone_name = "pix.immo"
